### ISSUE TITLE
Passing values with event

### ISSUE THREAD

**Issue by bcomnes** [yoshuawuyts/fsm-event#9]
Is there a way, or is it unwise, to allow passing of arguments to state transitions?

e.g. `m('play', 'path/to/some/file')`

```js
m.on('PLAYING', (arg1) => console.log(arg1) // 'path/to/some/file')
```

**Comment by yoshuawuyts** [comment]
uehhhhhhhhhh, it's been 2 years - I don't see any particular reason why that wouldn't be useful in some cases

**Comment by bcomnes** [comment]
Meh. Maybe
